name: CD - FTP Deploy

on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy on FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.CD_HOST }}
          username: ${{ secrets.CD_USERNAME }}
          password: ${{ secrets.CD_PASSWORD }}
