name: CD - Deploy via FTP/FTPS/SFTP

on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Déploiement direct du repo (on exclut .git, tests, var, etc. via l'action)
      # Si tu préfères ne déployer qu'un dossier "build" ou "deploy", change local-dir plus bas.
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}  
          port: ${{ secrets.FTP_PORT }}      
          local-dir: ./                                    #
          # Conserve l'état de sync côté serveur pour n'envoyer que les diffs
          state-name: .ftp-deploy-sync-state.json
          # Exclusions utiles pour un projet Symfony
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            var/**
            tests/**
            **/.DS_Store
            **/Thumbs.db
          # Verbose aide au debug
          log-level: verbose
          # passe à true si tu veux forcer un nettoyage distant (⚠️ supprime ce qui n'existe plus localement)
          dangerous-clean-slate: false
