name: CD - SFTP (password)

on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      HOST: ${{ secrets.SFTP_HOST }}
      PORT: ${{ secrets.SFTP_PORT }}
      USER: ${{ secrets.SFTP_USER }}
      PASS: ${{ secrets.SFTP_PASSWORD }}
      REMOTE_DIR: ${{ secrets.SFTP_REMOTE_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build deploy folder
        run: |
          mkdir -p deploy
          rsync -a \
            --exclude '.git/' --exclude '.github/' \
            --exclude 'node_modules/' --exclude 'var/' --exclude 'tests/' \
            ./ deploy/

      - name: Install sshpass
        run: |
          sudo apt-get update -y
          sudo apt-get install -y sshpass

      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "$PORT" "$HOST" >> ~/.ssh/known_hosts

      - name: SFTP preflight (pwd) - verbose
        run: |
          sshpass -p "$PASS" sftp -o StrictHostKeyChecking=yes -P "$PORT" -vvv "$USER@$HOST" <<< "pwd"

      - name: Ensure remote dir exists
        run: |
          sshpass -p "$PASS" sftp -o StrictHostKeyChecking=yes -P "$PORT" "$USER@$HOST" <<EOF
          -mkdir $REMOTE_DIR
          quit
          EOF

      - name: Upload (recursive)
        run: |
          sshpass -p "$PASS" sftp -o StrictHostKeyChecking=yes -P "$PORT" "$USER@$HOST" <<EOF
          cd $REMOTE_DIR
          put -r deploy/*
          quit
          EOF
