name: CD - Deploy via FTP/FTPS/SFTP

on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}  
          port: ${{ secrets.FTP_PORT }}    
          server-dir: ${{ secrets.FTP_REMOTE_DIR }}   
          local-dir: ./
          state-name: .ftp-deploy-sync-state.json
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            var/**
            tests/**
            **/.DS_Store
            **/Thumbs.db
          log-level: verbose
          dangerous-clean-slate: false
