name: CD - FTPS (lftp)

on:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      HOST: ${{ secrets.FTP_HOST }}
      PORT: ${{ secrets.FTP_PORT }}
      USER: ${{ secrets.FTP_USER }}
      PASS: ${{ secrets.FTP_PASSWORD }}
      REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Prépare un dossier propre à envoyer (évite .git, tests, etc.)
      - name: Build deploy folder
        run: |
          mkdir -p deploy
          rsync -a \
            --exclude '.git/' \
            --exclude '.github/' \
            --exclude 'node_modules/' \
            --exclude 'var/' \
            --exclude 'tests/' \
            ./ deploy/

      - name: Install lftp
        run: |
          sudo apt-get update -y
          sudo apt-get install -y lftp

      # (Optionnel) Test de connectivité et bannière
      - name: FTPS preflight
        run: |
          lftp -u "$USER","$PASS" "ftp://$HOST:$PORT" -e "
            set ftp:ssl-force true;
            set ftp:ssl-allow true;
            set ftp:passive-mode true;
            set ssl:verify-certificate false;
            debug 3;
            pwd;
            bye;
          "

      # Crée le répertoire distant si nécessaire
      - name: Ensure remote dir exists
        run: |
          lftp -u "$USER","$PASS" "ftp://$HOST:$PORT" -e "
            set ftp:ssl-force true;
            set ftp:ssl-allow true;
            set ftp:passive-mode true;
            set ssl:verify-certificate false;
            mkdir -p $REMOTE_DIR;
            bye;
          "

      # Upload en miroir (reverse mirror) — met à jour, n’envoie que les fichiers modifiés
      - name: Upload (mirror -R)
        run: |
          lftp -u "$USER","$PASS" "ftp://$HOST:$PORT" -e "
            set ftp:ssl-force true;
            set ftp:ssl-allow true;
            set ftp:passive-mode true;
            set ssl:verify-certificate false;
            set xfer:clobber on;
            set net:timeout 20;
            set net:max-retries 2;
            set net:reconnect-interval-base 5;
            mirror -R --only-newer --verbose=1 --parallel=4 \
              --exclude-glob .git/ --exclude-glob .github/ \
              --exclude-glob node_modules/ --exclude-glob var/ --exclude-glob tests/ \
              deploy/ $REMOTE_DIR;
            bye;
          "
