name: CI/CD Pipeline

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  test:
    name: Run PHPUnit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_sqlite
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist --no-scripts

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --testdox --colors=always

  deploy:
    name: Deploy on FTP
    runs-on: ubuntu-latest
    needs: test
    if: ${{ success() }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Install Composer dependencies
        run: composer install --no-dev --no-interaction --optimize-autoloader

      - name: Deploy on FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.CD_HOST }}
          username: ${{ secrets.CD_USERNAME }}
          password: ${{ secrets.CD_PASSWORD }}
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/tests/**
            var/**
          state-name: .ftp-deploy-sync-state.json
          log-level: verbose
