name: CI/CD Pipeline

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_sqlite
          tools: composer:v2
      - run: composer install --no-interaction --prefer-dist
      - run: vendor/bin/phpunit --testdox --colors=always

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ success() }}
    env:
      APP_ENV: prod
      APP_DEBUG: 0
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo, pdo_mysql, intl
          tools: composer:v2

      - name: Install Composer dependencies (prod, no scripts)
        run: composer install --no-dev --no-interaction --optimize-autoloader --no-scripts

      - name: Deploy on FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.CD_HOST }}
          username: ${{ secrets.CD_USERNAME }}
          password: ${{ secrets.CD_PASSWORD }}
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/tests/**
            **/.DS_Store
            **/Thumbs.db
          state-name: .ftp-deploy-sync-state.json
          log-level: verbose
