name: PHPUnit Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_sqlite
          tools: composer:v2
          coverage: none

      # Validation souple (n'échoue pas la CI si non publiable)
      - name: Validate composer.json (non-strict)
        run: composer validate --no-check-publish

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Prepare test environment
        run: |
          mkdir -p var
          touch var/data_test.db

      - name: Run PHPUnit
        run: vendor/bin/phpunit -v --colors=always
